name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
          
      - name: Rust Cache
        uses: swatinem/rust-cache@v2
        
      - name: Check formatting
        run: cargo fmt --all -- --check
        
      - name: Clippy (Default / std)
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Clippy (no_std)
        run: cargo clippy --no-default-features --lib --tests -- -D warnings
        
      - name: Run tests (Default / std)
        run: cargo test --all --verbose

      - name: Run tests (no_std)
        run: cargo test --no-default-features --verbose